= Docker examples
include::commonhead.adoc[]


== Prepare apache+php+pg image

php8pg contains the stuff to create an image containing apache, php 8 and the things needed
to connect to a postgres database.

In there run `docker build -t "php8pg"`.
An initial run may take a while, because some stuff has to be compile.

To test it, spin it up with `docker run -d --name=php8pg_test -p "18080:80" php8pg `.

You will use this image later on, but typically do not have configure it any further.

Point your browser at http://localhost:18080, and you should see the php configuration.

When satisfied with the result, spin the *container* down with `docker stop php8pg_test` and remove it with `docker rm php8pg_test`.

You need the *image*, not the container.


== refstuff contains a working example

refstuff defines two containers, named db and web.
The containers are configured with a docker-compose.yml file

The yml file uses one secret that is taken form the [red]`.env` file
which is NOT present in the repo for obvious reasons.

The .env file should contain one line declaring the PG_PASSWORD key

[source,sh]
----
PG_PASSWORD=changeme
----


DO NOT add/commit this .env file, but rather ignore it in the .gitignore file.

You should of course change the password to a better value that you keep to your selves.
You only need it on your machine.

== Using a database with PHP PDO style

The database handling style in these examples is modeled after java JDBC.

We use PHP/PDO as the basis and added two classes that make PDO behave almost the same as JDBC,
in particular regarding how to get a _named_ data source, without having to deal with database credentials in all source files.

The datasource (lib/PDODataSource.php) picks up the database settings from a file `etc/db_settings.php` outside the web-root.


=== Simple select with constant query expression
.Simple usage, select
[source,sql]
----
$sql = <<<'SQL'
select  pres.id as pres_id,
        pres.name as pres_name,
        years_served,
        party,
        state.name as state_name,
        year_entered
    from  president  pres
    join state on(state_id_born=state.id)
    where state.name=? and pres.party=?
SQL;
$ds = (new PDODataSource("presidents"))->setHost('db'); //<1>
$conn = $ds->getConnection();
$stmt = $conn->prepare($sql); //<2>
while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
    printRow($row, $colAlign, $columnCount); //<3>
}
----

<1> Only name the database and optionally the host, if it is not localhost.
<2> Always use a prepared statement.
<3> printRow is a simple method, left as an exercise.

The sql code above uses single or *strong* quotes. The string inside strong quotes
is not interpolated (or substituted), so this avoids picking up variables and implicitly avoids
sql injections, because strong quotes are not prone to injection (or substitution).


=== Select with parameters

.sql query text
[source,sql]
----
$queryText1 = <<<'SQL'
with inp as (
         select ?::date start_reservation,?::date end_reservation, ?::integer as item_id, ?::integer as customer_id
     ),
     validres as (
         select start_reservation cstart_reservation, greatest(start_reservation+1,end_reservation) cend_reservation
          from inp
     ),
     cost as (
          select item_cost_per_day*(cend_reservation - cstart_reservation) rcost
          from validres,rental_items join inp on (inp.item_id=rental_items.item_id)
     ),
     makeres as (
          insert into reservations (during, item_id, for_customer,reservation_cost)
          select daterange(cstart_reservation,cend_reservation), item_id, customer_id, rcost
          from inp,validres,cost
          returning  *
  )
  -- final update to customer credit
  update customers set credit=credit-(select reservation_cost from makeres) where customer_id=customer_id
    returning *
SQL;
----

<1> start by making the parameters meaningful
<2> make sure the reservation is at least for one day, meaning distance between start and end is 1.
   note the use of the greatest function, max is reserved for max in columns (vertically), greatest selects max in row (horizontally).
  The expression makes sure that at least one day has to be payed for.
<3> use corrected range and cost per item for item table to compute total cost.
<4> use the computed/corrected values to store.

.input sanitation and function call
[source,php]
----
$dates =preg_split("/\s\-\s/",$_POST['dates']);
$regex_filter=['options' =>[ 'regexp'=> '/^\d{4}-\d{2}-\d{2}/']];
$start_date = filter_var($dates[0], FILTER_VALIDATE_REGEXP, $regex_filter);
$end_date   = filter_var($dates[1], FILTER_VALIDATE_REGEXP, $regex_filter);
$item= filter_input(INPUT_POST,'item',FILTER_SANITIZE_NUMBER_INT);
$customer= filter_input(INPUT_POST,'customer',FILTER_SANITIZE_NUMBER_INT);
$arguments = ['date_from' => $dates[0],
    'date_to' => $dates[1],
    'item' => $item,
    'account' => $customer];

makeReservation($con, $arguments );
----


.transactional make a reservation
[source,php]
----
/**
 * Make a reservation. At least two tables are involved, the credits table and the resource (what to reserve) table.
 * Remember that in php, an array is also a hashmap with key,value pairs
 * @param PDOConnection $conn
 * @param array $reservationParams
 */
function makeReservation(PDO $conn, array $reservationParams) {
    global $queryText1, $queryText2, $queryText3;
    try {
        $conn->beginTransaction();
        //echo "<pre>$queryText1</pre>";
        $stmt1 = $conn->prepare($queryText1);

        $stmt1->execute([
            $reservationParams['date_from'],
            $reservationParams['date_to'],
            $reservationParams['item'],
            $reservationParams['account'],
        ]);
        $row = $stmt1->fetch(PDO::FETCH_ASSOC);
        $totalCost=$row['reservation_cost'];

        $stmt2 = $conn->prepare($queryText2);
        $stmt2->execute([
            $totalCost,
            $reservationParams['account']
        ]);
        $conn->commit();
        //echo "<pre>$queryText2</pre>";
        print_simple_table($conn, $queryText3, [$reservationParams['account']], 'transactions');
    } catch (PDOException $ex) {
        echo "<div class='errors'><h3 >transaction failed with</h3>
              <pre >" . $ex->getMessage() . "</pre>
             </div>";
        $conn->rollBack();
    }
}
----
