version : "3.9"

services:
    web:
        image: "php8pg"
        ports:
            - "8080:80"
        volumes:
            - ./web:/var/www
        depends_on: 
            - db  
    db:
        image: "postgres:13.4"
        volumes: 
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        ports:
            - "5433:5432"
