= Application structure
version 1.0 Pieter van den Hombergh
:source-highlighter: highlightjs
:highlightjs-theme: agate
:highlightjs-linenums-mode: inline


This application is composed of two services, each in its own container. +
The services are:

. the database called db, whose container will have _db_ in its name.
. the web application called web, whose container will have _web_ in its name.

In the docker-compose.yml file, each service is named and has its own section.

== web
The stuff that is under the web directory will be used as a volume te the web service and is mounted (is visible) as `/var/www` inside the resulting containner. The dedault site as defined by the standard apache configuration is [blue]`/var/www/html`, which makes the html directory that resides under the directory web visible and exposed to the (inter)net by the apache server. All files in there are potentially callable via a browser through a url.
The file name extension will be used by the apache server to determine if the file should be passed as is or being processed, as with php files which are interpreted by the php interpreter. The resulting output will then be determined by the php logic in such file.

== db
The stuff that is under the db directory is specific to the db service. The initdb.d directory is mounted under `/docker-entrypoint-initdb.d`, where
it will be used (once) at the first container startup. The files in db/initdb.d are processed in lexical order, which makes it useful to ensure that the names of the files in that directory have some fixed order. Common is to prefix the files with some numbers, like in the example:

. 10_db_users.sql
. 11_databases.sql
. 20_president-full.sql
. 21_hotel_california.sql

The files define the users the application wants to use, including their passwords, then creates the databases
and after that defines the schema and initial data per database.

The web service uses the database and therefor needs to know the hostname, database username, database name and database userpassword.
To keep this information away from a directory where it can be leaked, we have put that in a separate directory outside of the html directory.
Common is to use `etc` as a name for such a config file containing directory.
The php application needs to know the name of the file so it can include it without exposing its content.
In this example the file is called db_settings.php.
This file itself includes the password file in the same directory.
This later file is small and it is best to NOT commit and push it to the repo, because this would mean that you publish your secrets, which not only sound
stupid but really is.
What

.Settings file `web/etc/db_settings.php`
[source,php]
----
include::web/etc/db_settings.php[]
----

.password template file `web/etc/dbpassword.php-template`
[source,php]
----
include::web/etc/dbpassword.php-template[]
----

This is a template file only. +
Copy it to the file without -template at the end, but make sure you do not commit that resulting file. +
Best is to add that file name to .gitignore.
